name: Mirror to Repo B

on:
  push:
    branches:
      - main  # or any branch you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Push to Repo B
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add mirror https://RabiulHassanJomman:${{ secrets.MIRROR_TOKEN }}@github.com/RabiulHassanJomman/copy-of-orbitsix.git
          git push mirror main
